version: '3'
services:
  cache_server:
    build:
      context: ./cache_server/
    container_name: varnish
    depends_on:
      - web_server
    volumes:
      - ./cache_server/default.vcl:/etc/varnish/default.vcl
      - ./cache_server/varnish:/etc/default/varnish
      - ./cache_server/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    ports:
      - "80:80"
      - "6082:6082"
    links:
      - web_server

  web_server:
    build:
      context: ./web_server/
    container_name: apache2
    volumes:
      - ./magento2:/var/www/html  
      - ./web_server/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    ports:
      - "8080:8080"
    links:
      - database_server

  database_server:
    build:
      context: ./database_server/
      args:
        - mysql_password=mention_your_mysql_root_password
        - mysql_database=mention_your_database_name
    container_name: mysql
    volumes: 
      - ./database_server/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - ./database_server/mysql.sh:/etc/mysql.sh
    ports:
      - "3306:3306"
